### ISSUE TITLE
EventEmitter memory leak detected when running 'get'

### ISSUE THREAD

**Issue by matiu** [juliangruber/multilevel#68]
After our client runs for a couple of hours, when calling
``` javascript
db.get(xxx, function(...
```

we get:

``` javascript
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
   at Db.EventEmitter.addListener (events.js:160:15)
   at Db.addEventListener.Db.on (/xx/node_modules/multilevel/lib/client.js:110:13)
   at Db.EventEmitter.once (events.js:185:8)
   at Db._queue (/xx/node_modules/multilevel/lib/client.js:209:13)
   at Db.db.(anonymous function) [as get] (/opt/xx/node_modules/multilevel/lib/client.js:173:10)
  [...]
```
1) Any idea what could trigger this? This is a normal nodejs server, running with nodejs cluster (nr of instances = 4)
2) Since this exception happens async, and it is not catch and returned as 'err', it stops the execution. It should be catch and return as err.

thanks a lot.

**Comment by juliangruber** [comment]
Can you tell me which event emitters you added on `db`? Multilevel itself only registers `.on('open', fn)`.

**Comment by juliangruber** [comment]
And you can catch those running `db.on('error', function(err){ // your error handler })`
